name: puzzle-a-day
version: 0.0.0

ghc-options: -Wall -Werror -Wcompat -O2
default-extensions:
  - ImportQualifiedPost

library:
  source-dirs: src/
  dependencies:
    - array
    - base
    - containers
    # genetic algorithm
    - MonadRandom
    - multiset
    - parallel

executable:
  main: app/Main.hs
  ghc-options:
    # genetic algorithm
    - -threaded
    - -with-rtsopts=-N
  dependencies:
    - base
    - optparse-applicative
    - puzzle-a-day
    - time
