name: puzzle-a-day
version: 0.0.0

ghc-options: -Wall -Werror -Wcompat
default-extensions:
  - ImportQualifiedPost

library:
  source-dirs: src/
  dependencies:
    - array
    - base
    - containers

executable:
  main: app/Main.hs
  ghc-options: -threaded -O2
  dependencies:
    - base
    - puzzle-a-day
    - time

tests:
  puzzle-a-day-tests:
    main: test/Main.hs
    dependencies:
      - base
      - puzzle-a-day
      - tasty
      - tasty-hunit

